"""Text-to-SQL API endpoints for natural language database queries.

This module provides endpoints for translating natural language questions
into SQL queries and executing them against the database.
"""

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    Request,
)

from src.app.agents.text_to_sql import get_text_sql_agent
from src.app.api.security.limiter import limiter
from src.app.api.v1.auth import get_current_session
from src.app.api.v1.dtos.text_to_sql import (
    TextSQLRequest,
    TextSQLResponse,
)
from src.app.core.common.config import settings
from src.app.core.common.logging import logger
from src.app.core.session.session_model import Session

router = APIRouter()


@router.post("/query", response_model=TextSQLResponse)
@limiter.limit(settings.RATE_LIMIT_ENDPOINTS["text_to_sql"][0])
async def text_to_sql_query(
    request: Request,
    sql_request: TextSQLRequest,
    session: Session = Depends(get_current_session),
):
    """Submit a natural language query to be translated into SQL and executed.

    Accepts a natural language question about the database and returns
    the results generated by the Text-to-SQL Deep Agent.

    Args:
        request: The FastAPI request object for rate limiting.
        sql_request: The request containing the natural language query.
        session: The current session from the auth token.

    Returns:
        TextSQLResponse: The agent's response messages.

    Raises:
        HTTPException: If there's an error processing the request.
    """
    try:
        logger.info(
            "text_to_sql_request_received",
            session_id=session.id,
            query_length=len(sql_request.query),
        )

        agent = await get_text_sql_agent()
        result = await agent.agent_invoke(
            {"query": sql_request.query},
            session.id,
            user_id=session.user_id,
        )

        logger.info("text_to_sql_request_processed", session_id=session.id)

        return TextSQLResponse(messages=result)
    except Exception as e:
        logger.error(
            "text_to_sql_request_failed",
            session_id=session.id,
            error=str(e),
            exc_info=True,
        )
        raise HTTPException(status_code=500, detail=str(e))
